In [1]:
import numpy as np
from sklearn.decomposition import PCA

# Sample data matrix X
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Step 1: Center the data
X_centered = X - X.mean(axis=0)

# Step 2: Perform SVD
U, s, Vt = np.linalg.svd(X_centered)

# Step 3: Project the data onto the first 2 principal components
W2 = Vt.T[:, :2]
X2D = X_centered.dot(W2)

print("Principal Components (Direct SVD):")
print(W2)
print("Projected Data (Direct SVD):")
print(X2D)


Principal Components (Direct SVD):
[[ 0.57735027 -0.81649658]
 [ 0.57735027  0.40824829]
 [ 0.57735027  0.40824829]]
Projected Data (Direct SVD):
[[-5.19615242e+00 -1.33226763e-15]
 [ 0.00000000e+00  0.00000000e+00]
 [ 5.19615242e+00  1.33226763e-15]]


In [2]:
from sklearn.decomposition import PCA

# Sample data matrix X
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Step 1: Instantiate PCA
pca = PCA(n_components=2)
# pca = PCA(n_components=0.95) high variance 


# Step 2: Fit PCA
pca.fit(X)

# Step 3: Transform Data
X2D = pca.transform(X)

print("Principal Components (Scikit-Learn PCA):")
print(pca.components_.T)
print("Projected Data (Scikit-Learn PCA):")
print(X2D)


Principal Components (Scikit-Learn PCA):
[[ 0.57735027 -0.81649658]
 [ 0.57735027  0.40824829]
 [ 0.57735027  0.40824829]]
Projected Data (Scikit-Learn PCA):
[[-5.19615242e+00 -1.33226763e-15]
 [ 0.00000000e+00  0.00000000e+00]
 [ 5.19615242e+00  1.33226763e-15]]
