In [7]:
from sklearn.datasets import load_iris
iris = load_iris()

In [8]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [16]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [14]:
import pandas as pd
df = pd.DataFrame(data=iris["data"],columns=iris['feature_names'])
df['target'] = iris['target']
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [18]:
# Correlation

correlation_cal = df.corr()['target'].abs().sort_values(ascending=True)
print(correlation_cal)

sepal width (cm)     0.426658
sepal length (cm)    0.782561
petal length (cm)    0.949035
petal width (cm)     0.956547
target               1.000000
Name: target, dtype: float64


In [24]:
# iris virginica or not


# Chososing two column one independent 
# most corellated one and other the target column 
# where we are transforming to a new frame where if virginica
# 1 else 0 
import numpy as np
X = iris["data"][:,3:]
# X
y=(iris["target"]==2).astype(np.int64)
y 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)

In [29]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()

clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
y_probability = clf.predict_proba(X_test)

In [31]:
# Displaying the predicted classes
print("Predicted classes:", y_pred)

# Displaying the predicted probabilities
print("Predicted probabilities:")
print(y_probability)

Predicted classes: [0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 1
 0]
Predicted probabilities:
[[0.92486879 0.07513121]
 [0.85155743 0.14844257]
 [0.99618352 0.00381648]
 [0.99441922 0.00558078]
 [0.92486879 0.07513121]
 [0.07924573 0.92075427]
 [0.72776684 0.27223316]
 [0.98266447 0.01733553]
 [0.99618352 0.00381648]
 [0.79658657 0.20341343]
 [0.21293579 0.78706421]
 [0.21293579 0.78706421]
 [0.99618352 0.00381648]
 [0.64601046 0.35398954]
 [0.28382927 0.71617073]
 [0.36731051 0.63268949]
 [0.99618352 0.00381648]
 [0.79658657 0.20341343]
 [0.92486879 0.07513121]
 [0.64601046 0.35398954]
 [0.99184598 0.00815402]
 [0.64601046 0.35398954]
 [0.07924573 0.92075427]
 [0.99441922 0.00558078]
 [0.99618352 0.00381648]
 [0.85155743 0.14844257]
 [0.64601046 0.35398954]
 [0.99618352 0.00381648]
 [0.79658657 0.20341343]
 [0.99739152 0.00260848]
 [0.79658657 0.20341343]
 [0.36731051 0.63268949]
 [0.99184598 0.00815402]
 [0.21293579 0.78706421]
 [0.79658657 0.20341343]
 [

In [32]:
x_multi = iris["data"][:,[2,3]]
y_multi = iris["target"]

In [37]:
X_train_multi,X_test_multi,y_train_multi,y_test_multi = train_test_split(x_multi,y_multi,test_size=0.25)

In [38]:
softmax = LogisticRegression(multi_class="multinomial",solver="lbfgs")

softmax.fit(X_train_multi,y_train_multi)

LogisticRegression(multi_class='multinomial')

In [39]:
y_pred_multi = softmax.predict(X_test_multi)
y_prob_multi_= softmax.predict_proba(X_test_multi)

In [41]:
print("Predicted classes (multi-class):", y_pred_multi)

# Displaying the predicted probabilities for multi-class logistic regression
print("Predicted probabilities (multi-class):")
print(y_prob_multi_)

Predicted classes (multi-class): [0 2 0 0 2 2 1 1 0 0 1 2 1 1 2 2 1 2 1 0 0 2 1 0 0 1 1 1 1 2 1 0 0 1 1 1 2
 1]
Predicted probabilities (multi-class):
[[9.69247929e-01 3.07518826e-02 1.88099404e-07]
 [7.82991202e-07 7.58151301e-03 9.92417704e-01]
 [9.47919739e-01 5.20795974e-02 6.63586235e-07]
 [9.69918738e-01 3.00811217e-02 1.40089918e-07]
 [7.08782505e-04 3.31167095e-01 6.68124122e-01]
 [2.25038064e-06 3.14549515e-02 9.68542798e-01]
 [2.43630289e-02 9.29783286e-01 4.58536851e-02]
 [8.77426745e-02 8.98273590e-01 1.39837350e-02]
 [9.81185732e-01 1.88141726e-02 9.52999143e-08]
 [9.76194102e-01 2.38057828e-02 1.15622562e-07]
 [1.87920663e-03 5.07048498e-01 4.91072296e-01]
 [5.72888248e-04 2.73830773e-01 7.25596339e-01]
 [3.27563081e-02 9.39240291e-01 2.80034007e-02]
 [9.70966013e-04 5.38909899e-01 4.60119135e-01]
 [2.37507964e-04 1.92163806e-01 8.07598686e-01]
 [7.31651982e-05 1.02507866e-01 8.97418969e-01]
 [1.39505955e-03 5.95133422e-01 4.03471518e-01]
 [1.28169311e-03 4.49934767e-01 5

In [42]:
from sklearn.metrics import r2_score
print(r2_score(y_test_multi,y_pred_multi))


0.8744493392070485
