In [1]:
from sklearn.datasets import load_iris
iris = load_iris()

In [2]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [3]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [4]:
import pandas as pd
df = pd.DataFrame(data=iris["data"],columns=iris['feature_names'])
df['target'] = iris['target']
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [5]:
# Correlation

correlation_cal = df.corr()['target'].abs().sort_values(ascending=True)
print(correlation_cal)

sepal width (cm)     0.426658
sepal length (cm)    0.782561
petal length (cm)    0.949035
petal width (cm)     0.956547
target               1.000000
Name: target, dtype: float64


In [28]:
# iris virginica or not


# Chososing two column one independent 
# most corellated one and other the target column 
# where we are transforming to a new frame where if virginica
# 1 else 0 

import numpy as np
X = iris["data"][:,3:]
X
y=(iris["target"]==3).astype(np.int64)
# y 

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)

In [8]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()

clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
y_probability = clf.predict_proba(X_test)



In [9]:
# Displaying the predicted classes
print("Predicted classes:", y_pred)

# Displaying the predicted probabilities
print("Predicted probabilities:")
print(y_probability)

Predicted classes: [0 0 0 1 0 0 0 0 1 1 0 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 1 1
 0]
Predicted probabilities:
[[0.99588327 0.00411673]
 [0.99588327 0.00411673]
 [0.62501629 0.37498371]
 [0.3457442  0.6542558 ]
 [0.91874272 0.08125728]
 [0.84018289 0.15981711]
 [0.78188605 0.21811395]
 [0.70967235 0.29032765]
 [0.43661754 0.56338246]
 [0.14350316 0.85649684]
 [0.70967235 0.29032765]
 [0.07227281 0.92772719]
 [0.78188605 0.21811395]
 [0.26489159 0.73510841]
 [0.78188605 0.21811395]
 [0.62501629 0.37498371]
 [0.99718919 0.00281081]
 [0.05044126 0.94955874]
 [0.84018289 0.15981711]
 [0.78188605 0.21811395]
 [0.99718919 0.00281081]
 [0.84018289 0.15981711]
 [0.99397427 0.00602573]
 [0.19724619 0.80275381]
 [0.99588327 0.00411673]
 [0.99118787 0.00881213]
 [0.43661754 0.56338246]
 [0.99397427 0.00602573]
 [0.99588327 0.00411673]
 [0.99588327 0.00411673]
 [0.99397427 0.00602573]
 [0.07227281 0.92772719]
 [0.99118787 0.00881213]
 [0.62501629 0.37498371]
 [0.98123794 0.01876206]
 [

In [10]:
x_multi = iris["data"][:,[2,3]]
y_multi = iris["target"]

In [11]:
X_train_multi,X_test_multi,y_train_multi,y_test_multi = train_test_split(x_multi,y_multi,test_size=0.25)

In [12]:
softmax = LogisticRegression(multi_class="multinomial",solver="lbfgs")

softmax.fit(X_train_multi,y_train_multi)

LogisticRegression(multi_class='multinomial')

In [13]:
y_pred_multi = softmax.predict(X_test_multi)
y_prob_multi_= softmax.predict_proba(X_test_multi)

In [14]:
print("Predicted classes (multi-class):", y_pred_multi)

# Displaying the predicted probabilities for multi-class logistic regression
print("Predicted probabilities (multi-class):")
print(y_prob_multi_)

Predicted classes (multi-class): [1 2 1 0 2 0 0 1 0 1 2 1 1 2 0 1 1 1 0 2 2 0 0 1 1 1 1 2 2 0 1 0 0 2 2 1 2
 2]
Predicted probabilities (multi-class):
[[5.22174011e-03 7.79418111e-01 2.15360148e-01]
 [3.42511751e-05 5.39999025e-02 9.45965846e-01]
 [1.77098573e-02 9.04003537e-01 7.82866054e-02]
 [9.59983945e-01 4.00154879e-02 5.67412901e-07]
 [6.67763452e-07 1.30389292e-02 9.86960403e-01]
 [9.67008828e-01 3.29905416e-02 6.30104160e-07]
 [9.44083400e-01 5.59144266e-02 2.17381999e-06]
 [6.51445371e-03 7.72181257e-01 2.21304290e-01]
 [9.68881622e-01 3.11180256e-02 3.52438030e-07]
 [2.62739771e-02 9.43912024e-01 2.98139992e-02]
 [1.06731330e-03 3.92962437e-01 6.05970250e-01]
 [4.76105124e-03 7.32431376e-01 2.62807572e-01]
 [1.82271816e-01 8.13471922e-01 4.25626267e-03]
 [5.49059918e-05 6.66982454e-02 9.33246849e-01]
 [9.59983945e-01 4.00154879e-02 5.67412901e-07]
 [3.03223895e-02 9.18909682e-01 5.07679286e-02]
 [1.58377852e-02 8.58750903e-01 1.25411312e-01]
 [1.16562733e-01 8.76250808e-01 7

In [15]:
from sklearn.metrics import r2_score
print(r2_score(y_test_multi,y_pred_multi))


1.0
